version: '3.8'

services:
  app:
    image: room_chat_app:0.0.1
    environment:
      SPRING_DATASOURCE_URI: jdbc:mysql://db:3306/chatApp
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
    ports:
        - 8081:8081
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatApp
      MYSQL_USER: admin
      MYSQL_PASSWORD: root


