version: '3.8'

services:
  app:
    image: room_chat_app:latest
    container_name: room_chat_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chatApp?autoReconnect=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
        - 8081:8081
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatApp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
          - db_data:/var/lib/mysql # Persist MySQL data
volumes:
  db_data: # Named volume for MySQL persistence
