version: '3.8'

services:
  app:
    image: room_chat_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chatApp
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
        - 8081:8081
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chatApp
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306

